enymind_health_welcome:
    resource: "@EnymindHealthWelcomeBundle/Controller/"
    type:     annotation
    prefix:   /

enymind_health_secure:
    resource: "@EnymindHealthSecureBundle/Controller/"
    type:     annotation
    prefix:   /secure

login_check:
    pattern:   /secure/login
    
logout:
    pattern:   /secure/logout

enymind_health_secure_user:
    resource: "@EnymindHealthSecureBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /secure/user
    
enymind_health_secure_manage_entry_type:
    resource: "@EnymindHealthSecureBundle/Controller/EntryTypeController.php"
    type:     annotation
    prefix:   /secure/manage/types

# Internal routing configuration to handle ESI
_internal:
    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
    prefix:   /_internal
