jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Enymind\Bundle\Health\SecureBundle\Entity\User:
            algorithm: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        dbase:
            entity: { class: Enymind\Bundle\Health\SecureBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        registration:
            pattern: ^/secure/user/register$
            security: false
            anonymous: ~

        cred_sent:
            pattern: ^/secure/user/send$
            security: false
            anonymous: ~

        login:
            pattern: ^/login$
            security: false
            anonymous: ~

        secured_area:
            provider: dbase
            pattern: ^/secure/
            form_login:
                check_path: /secure/login
                login_path: /login
                always_use_default_target_path: true
                default_target_path: /secure/
            logout:
                path: /secure/logout
                target: /
