jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Enymind\Bundle\Health\SecureBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        administrators:
            entity: { class: EnymindHealthSecureBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false
            anonymous: ~

        secured_area:
            pattern:    ^/secure/
            form_login:
                check_path: /secure/login
                login_path: /login
                always_use_default_target_path: true
                default_target_path: /secure/
            logout:
                path:   /secure/logout
                target: /
